server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: countriesModule
        uri: http://localhost:3001/
        predicates:
        - Path=/customer/**
      - id: travelModule
        uri: http://localhost:3002/
        predicates:
        - Path=/account/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true